name: Terraform CI with Trivy and TFLint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: Validate and Analyze Terraform Code
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      # Step 3: Run terraform fmt
      - name: Run terraform fmt
        run: terraform fmt -check -recursive
        continue-on-error: true

      # Step 4: Validate Terraform configuration
      - name: Run terraform validate
        run: terraform validate
        continue-on-error: true

      # Step 5: Install TFLint for static analysis
      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      # Step 6: Run TFLint
      - name: Run TFLint
        run: tflint --init && tflint
        continue-on-error: true

      # Step 7: Run Trivy using official GitHub Action
      - name: Run Trivy config scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          ignore-policy: |
            aws/rds/disable_cluster_skip_final_snapshot
            aws/rds/enable_cluster_deletion_protection
        continue-on-error: true
