name: Terraform CI with Trivy

# Restrict permissions for this workflow
permissions:
  contents: read  # Only allow read access to the repository contents

on:
  # Trigger the workflow on push to the main branch
  push:
    branches:
      - main
  # Trigger the workflow on pull request to the main branch
  pull_request:
    branches:
      - main
  # Enable manual workflow run
  workflow_dispatch:

jobs:
  terraform:
    name: Validate and Lint Terraform
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code using the latest version of the action
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Terraform CLI using the latest version of the action
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      # Step 3: Run terraform fmt to ensure proper code formatting
      - name: Run terraform fmt
        run: terraform fmt -check -recursive

      # Step 4: Validate Terraform configuration for syntax errors
      - name: Run terraform validate
        run: terraform validate

      # Step 5: Install TFLint for static analysis
      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      # Step 6: Run TFLint to lint the Terraform configuration
      - name: Run TFLint
        run: tflint --init && tflint

      # Step 7: Install and run Trivy for security analysis
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh

      - name: Run Trivy for IaC scan
        run: |
          ./trivy iac --security-checks config .
