name: Terraform CI with Trivy and TFLint

on:
  # Trigger the workflow on push to the main branch
  push:
    branches:
      - main
  # Trigger the workflow on pull request to the main branch
  pull_request:
    branches:
      - main
  # Enable manual workflow run
  workflow_dispatch:

jobs:
  terraform:
    name: Validate and Analyze Terraform Code
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      # Step 3: Run terraform fmt to ensure proper code formatting
      - name: Run terraform fmt
        run: terraform fmt -check -recursive
        continue-on-error: true  # Continue even if formatting fails

      # Step 4: Validate Terraform configuration
      - name: Run terraform validate
        run: terraform validate
        continue-on-error: true  # Continue even if validation fails

      # Step 5: Install TFLint for static analysis
      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      # Step 6: Run TFLint to lint the Terraform configuration
      - name: Run TFLint
        run: tflint --init && tflint
        continue-on-error: true  # Continue even if linting fails

      # Step 7: Install Trivy for security analysis
      - name: Install Trivy
        run: |
          curl -sfL https://aquasecurity.github.io/trivy-repo/install.sh | sudo bash

      # Step 8: Run Trivy to perform a security check
      - name: Run Trivy config scan
        run: trivy config --skip-policy "aws/rds/disable_cluster_skip_final_snapshot" --skip-policy "aws/rds/enable_cluster_deletion_protection" .
        continue-on-error: true  # Continue even if Trivy finds issues
